### ISSUE TITLE
unsuccessful

### ISSUE THREAD

**Issue by MacOMNI** [portto/blocto-solana-web3-provider#4]
The attempt was unsuccessful. Can you provide Android IOS demo or link

**Comment by mghnmtt** [comment]
injected js 


     """  (function() {
          var config = {
            address: "\(address)",
            network: "\(network)"
          };
          const bloctoProvider = new window.BloctoSolana(config);
          window.solana = bloctoProvider;
          window.bloctoProvider = bloctoProvider;
        })();"""

for iOS

        [_config.userContentController addScriptMessageHandler:self name:@"blocto-solana"];
